return {
  ["workshop-1216718131"]={ configuration_options={ clean=true, lang=true, stack=true }, enabled=true },
  ["workshop-1275167632"]={
    configuration_options={
      collect_ability="on",
      container_size="9",
      hotkey_mypet="on",
      level_system="on",
      modlanguage="chinese",
      personal_machine="on",
      recipe_critterlab="off",
      unique_skill="on" 
    },
    enabled=true 
  },
  ["workshop-1301033176"]={ configuration_options={ LANG="simplified" }, enabled=true },
  ["workshop-1302830827"]={
    configuration_options={
      hallowed_nights=true,
      winters_feast=true,
      year_of_the_gobbler=true,
      year_of_the_pig=true,
      year_of_the_varg=true 
    },
    enabled=true 
  },
  ["workshop-1530801499"]={
    configuration_options={ Hunger_Cost=1, Ownership=false, Sanity_Cost=1 },
    enabled=true 
  },
  ["workshop-1796885039"]={
    configuration_options={
      Dig=false,
      GameMode=true,
      Hammer=false,
      Language=true,
      Sound=true,
      TotooriaSpeech=1,
      UIHeight=80,
      UIScale=0.75 
    },
    enabled=true 
  },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-439115156"]={
    configuration_options={
      avisual_musha="Bmm",
      avisual_pirate="BL",
      avisual_pirate_armor="pirate",
      avisual_princess="WSP",
      bodyguardwilson=0,
      craftgems="color",
      deathPenalty="on",
      dietmusha="normal",
      difficultdamage="normal",
      difficultdamage_range="normal",
      difficulthealth="normal",
      difficultmana="dmana_normal",
      difficultmusic="dmusic_normal",
      difficultover="monster1x",
      difficultrecipe="normal",
      difficultsanity="normal",
      difficultsleep="dsleep_normal",
      difficulttired="dtired_normal",
      difficultysniff="normal",
      favoritemusha="normal",
      frostblade3rd=3,
      incontainer=0,
      key=108,
      key10=110,
      key11=103,
      key12=116,
      key13=282,
      key14=283,
      key15=111,
      key2=114,
      key3=99,
      key4=120,
      key5=107,
      key6=122,
      key7=112,
      key8=118,
      key9=98,
      loudlightning="off",
      modlanguage="chinese",
      musha_incontainer=1,
      on_butterfly_shield=1,
      princess_taste="princess",
      shareitems=0,
      smartmusha="normal",
      stop_spawning=1 
    },
    enabled=true 
  },
  ["workshop-447092740"]={ configuration_options={  }, enabled=true },
  ["workshop-501385076"]={ configuration_options={ quick_harvest=true }, enabled=true },
  ["workshop-623749604"]={
    configuration_options={
      Craft="Normal",
      Destroyable="DestroyByAll",
      FoodSpoilage=1,
      Language="En",
      Position="Center",
      Slots=80 
    },
    enabled=true 
  },
  ["workshop-631648169"]={
    configuration_options={
      [""]=0,
      ["Boss公告"]=0,
      GlommerXue=false,
      Klaus_sack=false,
      Mod_Boss_1=false,
      Mod_Boss_10=false,
      Mod_Boss_11=false,
      Mod_Boss_12=false,
      Mod_Boss_13=false,
      Mod_Boss_14=false,
      Mod_Boss_15=false,
      Mod_Boss_16=false,
      Mod_Boss_17=false,
      Mod_Boss_18=false,
      Mod_Boss_19=false,
      Mod_Boss_2=false,
      Mod_Boss_20=false,
      Mod_Boss_3=false,
      Mod_Boss_4=false,
      Mod_Boss_5=false,
      Mod_Boss_6=false,
      Mod_Boss_7=false,
      Mod_Boss_8=false,
      Mod_Boss_9=false,
      WillowShao=false,
      XianZuoBiao=false,
      ["中Boss击杀公告"]=0,
      ["基本配置"]=0 
    },
    enabled=true 
  },
  ["workshop-656256171"]={
    configuration_options={ dont_give_dubloons=2, give_dubloons=1, position=1, rec_dubloon=3, rec_gold=3 },
    enabled=true 
  },
  ["workshop-666155465"]={
    configuration_options={
      chestB=-1,
      chestG=-1,
      chestR=-1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      lang="auto",
      show_food_units=-1,
      show_uses=-1 
    },
    enabled=true 
  },
  ["workshop-812713308"]={ configuration_options={ fireflies_fear=222, language=0 }, enabled=true },
  ["workshop-921583679"]={ configuration_options={ finiteuses=3 }, enabled=true } 
}
